import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";

import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Group IT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4">
        <h1 className="text-white">Home </h1>
      </div>
    </>
  );
};

export default Home;
